paths:
  dataset: "data/synthetic_dataset/yolo_ready"

config:
  model: "yolo26s-pose.pt" # Custom model found in project root
  resume: False
  epochs: 150
  imgsz: 640
  batch_size: 32 # Increased if GPU allows, adjust to 8 if OOM
  lr0: 0.01 # Standard starting LR
  dataset:
    train_ratio: 0.8
  images_extensions: ['.png', '.jpg', '.jpeg']
  device: '0' # Use '0' for first GPU or 'cpu'
  patience: 100
  rect: False
  pose: 20
  kobj: 2.0
  kpt_shape: [11, 3] # 11 keypoints (WindTurbine max)
  sigmas: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05] # Matching 11 kpts

Augmentations:
  degrees: 15
  scale: 0.5
  fliplr: 0 # Flip left to right
  mosaic: 0

Optimization_and_Hardware: 
  workers: 4
  cos_lr: True
  cache: ram 

output: 
  name: "train"

hydra:
  job:
    chdir: False
